server.port=8082

spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

spring.application.name=opendata

services.auth-url=${SERVICES_AUTH-URL:http://localhost:8080/api/auth}
services.mup-url=${SERVICES_MUP-URL:http://localhost:8081/api/zahtevi}

jwt.secret=tajni_kljuc_za_demo_treba_biti_duzi_za_prod
jwt.expiration=86400000

spring.security.user.name=opendata
spring.security.user.password=opendata123

logging.level.org.springframework.web.filter.CorsFilter=DEBUG
logging.level.org.springframework.web.cors=DEBUG
